# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import multiverse_pb2 as multiverse__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in multiverse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultiverseStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPower = channel.unary_unary(
                '/multiverse.Multiverse/SetPower',
                request_serializer=multiverse__pb2.PowerRequest.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.SetWakeUp = channel.unary_unary(
                '/multiverse.Multiverse/SetWakeUp',
                request_serializer=multiverse__pb2.WakeUpRequest.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.SetActiLine = channel.unary_unary(
                '/multiverse.Multiverse/SetActiLine',
                request_serializer=multiverse__pb2.ActiLineRequest.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.PcapStart = channel.unary_unary(
                '/multiverse.Multiverse/PcapStart',
                request_serializer=multiverse__pb2.Empty.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.PcapStop = channel.unary_unary(
                '/multiverse.Multiverse/PcapStop',
                request_serializer=multiverse__pb2.Empty.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.PcapSetName = channel.unary_unary(
                '/multiverse.Multiverse/PcapSetName',
                request_serializer=multiverse__pb2.PcapNameRequest.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.PcapDelete = channel.unary_unary(
                '/multiverse.Multiverse/PcapDelete',
                request_serializer=multiverse__pb2.PcapNameRequest.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.PcapDeleteAll = channel.unary_unary(
                '/multiverse.Multiverse/PcapDeleteAll',
                request_serializer=multiverse__pb2.Empty.SerializeToString,
                response_deserializer=multiverse__pb2.CommandReply.FromString,
                _registered_method=True)
        self.PcapGet = channel.unary_stream(
                '/multiverse.Multiverse/PcapGet',
                request_serializer=multiverse__pb2.PcapNameRequest.SerializeToString,
                response_deserializer=multiverse__pb2.PcapChunk.FromString,
                _registered_method=True)


class MultiverseServicer:
    """Missing associated documentation comment in .proto file."""

    def SetPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWakeUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiLine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PcapStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PcapStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PcapSetName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PcapDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PcapDeleteAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PcapGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiverseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPower': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPower,
                    request_deserializer=multiverse__pb2.PowerRequest.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'SetWakeUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWakeUp,
                    request_deserializer=multiverse__pb2.WakeUpRequest.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'SetActiLine': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiLine,
                    request_deserializer=multiverse__pb2.ActiLineRequest.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'PcapStart': grpc.unary_unary_rpc_method_handler(
                    servicer.PcapStart,
                    request_deserializer=multiverse__pb2.Empty.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'PcapStop': grpc.unary_unary_rpc_method_handler(
                    servicer.PcapStop,
                    request_deserializer=multiverse__pb2.Empty.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'PcapSetName': grpc.unary_unary_rpc_method_handler(
                    servicer.PcapSetName,
                    request_deserializer=multiverse__pb2.PcapNameRequest.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'PcapDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.PcapDelete,
                    request_deserializer=multiverse__pb2.PcapNameRequest.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'PcapDeleteAll': grpc.unary_unary_rpc_method_handler(
                    servicer.PcapDeleteAll,
                    request_deserializer=multiverse__pb2.Empty.FromString,
                    response_serializer=multiverse__pb2.CommandReply.SerializeToString,
            ),
            'PcapGet': grpc.unary_stream_rpc_method_handler(
                    servicer.PcapGet,
                    request_deserializer=multiverse__pb2.PcapNameRequest.FromString,
                    response_serializer=multiverse__pb2.PcapChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multiverse.Multiverse', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('multiverse.Multiverse', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Multiverse:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/SetPower',
            multiverse__pb2.PowerRequest.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWakeUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/SetWakeUp',
            multiverse__pb2.WakeUpRequest.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActiLine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/SetActiLine',
            multiverse__pb2.ActiLineRequest.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PcapStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/PcapStart',
            multiverse__pb2.Empty.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PcapStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/PcapStop',
            multiverse__pb2.Empty.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PcapSetName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/PcapSetName',
            multiverse__pb2.PcapNameRequest.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PcapDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/PcapDelete',
            multiverse__pb2.PcapNameRequest.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PcapDeleteAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multiverse.Multiverse/PcapDeleteAll',
            multiverse__pb2.Empty.SerializeToString,
            multiverse__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PcapGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/multiverse.Multiverse/PcapGet',
            multiverse__pb2.PcapNameRequest.SerializeToString,
            multiverse__pb2.PcapChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
